import type { Metadata } from "next";
import SmoothScrollProvider from "@/providers/smooth scroll";

import "./globals.scss";

export const metadata: Metadata = {
  title: {
    template: "%s | spider verse",
    default: "spider verse",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="overflow-x-clip">
        <SmoothScrollProvider>{children}</SmoothScrollProvider>
      </body>
    </html>
  );
}
